export const GET_POKEMONS = 'GET_POKEMONS'
export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS'
export const GET_POKEMONS_ERROR = 'GET_POKEMONS_ERROR'
export const GET_POKEMONS_CLEAR = 'GET_POKEMONS_CLEAR'

export const GET_POKEMON_DETAIL = 'GET_POKEMONS_DETAIL'
export const GET_POKEMON_DETAIL_SUCCESS = 'GET_POKEMONS_DETAIL_SUCCESS'
export const GET_POKEMON_DETAIL_ERROR = 'GET_POKEMONS_DETAIL_ERROR'
export const GET_POKEMON_DETAIL_CLEAR = 'GET_POKEMONS_DETAIL_CLEAR'