export const GET_HABITATS = 'GET_HABITATS'
export const GET_HABITATS_SUCCESS = 'GET_HABITATS_SUCCESS'
export const GET_HABITATS_ERROR = 'GET_HABITATS_ERROR'
export const GET_HABITATS_CLEAR = 'GET_HABITATS_CLEAR'

export const GET_HABITAT_DETAIL = 'GET_HABITAT_DETAIL'
export const GET_HABITAT_DETAIL_SUCCESS = 'GET_HABITAT_DETAIL_SUCCESS'
export const GET_HABITAT_DETAIL_ERROR = 'GET_HABITAT_DETAIL_ERROR'
export const GET_HABITAT_DETAIL_CLEAR = 'GET_HABITAT_DETAIL_CLEAR'